version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/trash_solutions
      - JWT_SECRET=abc123
      - CLOUDINARY_CLOUD_NAME=dkynnqsf8
      - CLOUDINARY_API_KEY=768317426178964
      - CLOUDINARY_API_SECRET=c7V6bdq4KkvISUV2yNLf09O6TWQ
    depends_on:
      - mongo
    command: npm run start

  mongo:
    image: mongo:6
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=trash_solutions

volumes:
  mongo_data:
